-- Create the profiles table to store user data
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  display_name text NULL,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create the subjects table (combining attendance data for simplicity)
CREATE TABLE public.subjects (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL,
  name text NOT NULL,
  created_at timestamptz NULL DEFAULT now(),
  attended integer NOT NULL DEFAULT 0,
  total integer NOT NULL DEFAULT 0,
  required_perc integer NOT NULL DEFAULT 75,
  CONSTRAINT subjects_pkey PRIMARY KEY (id),
  CONSTRAINT subjects_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;

-- Create the timetables table
CREATE TABLE public.timetables (
  id bigint GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid NOT NULL,
  day_of_week text NOT NULL, -- e.g., 'monday', 'tuesday'
  period integer NOT NULL,
  subject_id bigint NOT NULL,
  CONSTRAINT timetables_pkey PRIMARY KEY (id),
  CONSTRAINT timetables_subject_id_fkey FOREIGN KEY (subject_id) REFERENCES public.subjects(id) ON DELETE CASCADE,
  CONSTRAINT timetables_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);
ALTER TABLE public.timetables ENABLE ROW LEVEL SECURITY;

-- Create security policies

-- Profiles policies
CREATE POLICY "Users can view their own profile." ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update their own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Subjects policies
CREATE POLICY "Users can manage their own subjects." ON public.subjects FOR ALL USING (auth.uid() = user_id);

-- Timetables policies
CREATE POLICY "Users can manage their own timetable." ON public.timetables FOR ALL USING (auth.uid() = user_id);

-- Function to create a profile when a new user signs up
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$;

-- Trigger the function after a new user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
