import React from 'react';
import { Link } from 'react-router-dom';

const TermsPage = () => (
  <div className="gradient-bg min-h-screen text-white/90 flex flex-col items-center p-4 sm:p-8">
    <div className="w-full max-w-4xl">
      <header className="text-center mb-12">
        <Link to="/" className="inline-block mb-6">
          <div className="bg-white/5 backdrop-blur-lg rounded-full p-4 shadow-lg">
            <i className="fas fa-calendar-check text-5xl text-gradient"></i>
          </div>
        </Link>
        <h1 className="text-4xl md:text-5xl font-bold mb-4 text-gradient">Terms and Conditions</h1>
        <p className="text-lg opacity-80 mb-8">Last updated: September 7, 2025</p>
      </header>
      <main className="bg-white/5 backdrop-blur-lg rounded-xl shadow-xl p-6 sm:p-10 content-card leading-relaxed">
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">1. Acceptance of Terms</h2>
        <p>By accessing and using Punch.In Scholar Companion (the "Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this Service.</p>
        
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">2. Description of Service</h2>
        <p>The Service is a web-based application designed to help students track their academic attendance and utilize AI-powered tools for strategic planning. The features include, but are not limited to, attendance calculation, bunk planning, and AI-driven study suggestions. The Service is provided for informational and planning purposes only.</p>
        
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">3. User Responsibilities</h2>
        <p>You are responsible for the accuracy of the data you provide to the Service. You agree not to use the Service for any unlawful purpose or to engage in any activity that could harm the Service or its users. You are responsible for maintaining the confidentiality of your account and password.</p>
        
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">4. AI Features Disclaimer</h2>
        <p>The AI features within the Service are powered by Google's Gemini API. The suggestions and plans generated by the AI are for informational purposes only and should be treated as guidance, not as definitive advice. We are not responsible for any academic or personal outcomes resulting from following the AI's suggestions. The accuracy of AI-generated content, including holiday information, is not guaranteed.</p>
        
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">5. Intellectual Property</h2>
        <p>The Service and its original content, features, and functionality are and will remain the exclusive property of Aadithya Vimal and are protected by copyright and other intellectual property laws. You may not copy, modify, or distribute any part of the Service without prior written consent.</p>
        
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">6. Limitation of Liability</h2>
        <p>In no event shall we be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
        
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">7. Changes to Terms</h2>
        <p>We reserve the right to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.</p>
        
        <h2 className="text-[1.5rem] font-bold mb-4 border-b border-white/10 pb-2">8. Contact Us</h2>
        <p>If you have any questions about these Terms, please contact us at: <a href="mailto:aadithyavimal.work@gmail.com" className="text-indigo-400 hover:underline">aadithyavimal.work@gmail.com</a>.</p>
      </main>
      <div className="text-center mt-8">
        <Link to="/" className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 px-6 rounded-lg transition-all transform hover:scale-105 shadow-lg">
          Back to App
        </Link>
      </div>
    </div>
  </div>
);

export default TermsPage;
